import { D1CreateEndpoint } from "chanfana";
import { HandleArgs } from "../../types";
import { MistakeModel } from "./mistakeSchema";

export class MistakeCreate extends D1CreateEndpoint<HandleArgs> {
	_meta = {
		model: MistakeModel,
		fields: MistakeModel.schema.pick({
			// this is purposely missing id and created_at, they're generated by the DB
			original: true,
			correction: true,
			explanation: true,
			pattern: true,
			subpattern: true,
			context: true,
		}),
	};
}
